// Generated by https://quicktype.io
import 'package:flutter/cupertino.dart';

class Negocios {
  List<Negocio> items = [];
  Negocios.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;
    for (var item in jsonList) {
      final negocio = new Negocio.fromJsonMap(item);
      items?.add(negocio);
    }
  }
}

class Negocio {
  String idnegocio;
  String nombre;
  String descripcion;
  String logo;
  String horaApertura;
  String horaCierre;
  String telefono;
  String sitioWeb;
  String representante;
  int idSubCategoria;

  Negocio(
      {this.idnegocio,
      this.nombre,
      this.descripcion,
      this.logo,
      this.horaApertura,
      this.horaCierre,
      this.telefono,
      this.sitioWeb,
      this.representante,
      this.idSubCategoria});

  Negocio.fromJsonMap(Map<String, dynamic> json) {
    idnegocio = json["idnegocio"];
    nombre = json["nombre"];
    descripcion = json["descripcion"];
    logo = json["logo"];
    horaApertura = json["horaApertura"];
    horaCierre = json["horaCierre"];
    telefono = json["telefono"];
    sitioWeb = json["sitioWeb"];
    representante = json["representante"];
    idSubCategoria = json["idSubcategoria"];
  }

  getImage() {
    if (logo == null) {
      return AssetImage("assets/img/no-image.jpg");
    } else {
      return logo;
    }
  }

  getNombre() {
    if (nombre == null) {
      return "No 'nombre' provided";
    } else {
      return nombre;
    }
  }

  getDescription() {
    if (descripcion == null) {
      return "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.";
    } else {
      return descripcion;
    }
  }
}
